### ISSUE TITLE
运行报错是啥原因啊

### ISSUE THREAD

**Issue by yejinson** [xiatianaa/jdcoupon#1]
<img src='https://s2.loli.net/2022/05/28/riapAGVum4P6UJ1.png' title='quicker_5462f54a-ffcf-42bf-8b1e-077e3fe5115e.png' />
<img src='https://s2.loli.net/2022/05/28/dMj5NK3XlsrxJkn.png' title='quicker_b7058538-64a6-4d00-b139-9974d839d031.png' />

**Comment by xiatianaa** [comment]
res['sunCodeMsg']这里有问题，返回的res没有subcodemsg，可以把res打印出来看下

**Comment by yejinson** [comment]
> res['sunCodeMsg']这里有问题，返回的res没有subcodemsg，可以把res打印出来看下

我是小白，res怎么打印

**Comment by xiatianaa** [comment]
www.baidu.com
www.google.com
www.biying.com

**Comment by yejinson** [comment]
> [www.baidu.com](http://www.baidu.com) [www.google.com](http://www.google.com) [www.biying.com](http://www.biying.com)

<img src='https://s2.loli.net/2022/05/28/wvKsnCA7WQcyY1G.png' title='quicker_8499bc81-c3d9-4687-b3c0-f7dae95edc6e.png' />是这样吗？

**Comment by yejinson** [comment]
> res['sunCodeMsg']这里有问题，返回的res没有subcodemsg，可以把res打印出来看下

会不会是链接有问题 我用的api直链

> res['sunCodeMsg']这里有问题，返回的res没有subcodemsg，可以把res打印出来看下

应该是这样吧，提示未登录，这是啥原因啊？
<img src='https://s2.loli.net/2022/05/28/hXt3MevWVCucwGk.png' title='quicker_c1e75eab-c9b5-4f54-8a20-6538bf8aee82.png' />
